language: node_js
node_js:
  - 10

cache:
  directories:
  - "$HOME/.npm"

jobs:
  include:
    - stage: deploy
      script:
        - npm run build
        - |
            declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
            echo -ne "$GIT_PRIVATE_KEY" > $SSH_FILE
            chmod 600 "$SSH_FILE"
            echo -en "Host alternate-github\n  User git\n  HostName github.com\n  IdentityFile $SSH_FILE" >> $HOME/.ssh/config
        - git config --global user.email "travis@travis-ci.com"
        - git config --global user.name "Travis CI"
        - git clone alternate-github:imnotjames/whois-servers.git ./whois-servers
        - node build/index.js fetch --format=json > ./whois-servers/servers.json
        - cd ./whois-servers/
        - |
            if [ -n "$(git status --porcelain)" ]; then 
              git add servers.json
              git commit -m "$(printf 'Travis: Updating Server List\n\nhttps://travis-ci.com/%s/jobs/%s' $TRAVIS_REPO_SLUG $TRAVIS_JOB_ID)"
              npm version patch
              git push
              git push --tags
            fi
